spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

tour-api:
  service-key: ${TOUR_API_SERVICE_KEY}
  mobile-os: ETC
  mobile-app: ModuTrip
  response-type: json
  kor-service-base-url: https://apis.data.go.kr/B551011/KorService2
  kor-with-service-base-url: https://apis.data.go.kr/B551011/KorWithService2


tour-initial-load:
  enabled: false
  accessible-enabled: true
  general-enabled: false
  max-pages-per-run: 300
  cron: "0 10 21 * * *"
  zone: "Asia/Seoul"

tour-batch:
  enabled: true
  cron: "0 45 21 * * *"
  zone: Asia/Seoul
  # max-pages: 50
  detail-batch-size: 450

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-millis: 1800000
    refresh-token-expiration-millis: 1209600000
